In [1]:
from fastai.tabular.all import *

In [3]:
import pandas as pd #Pandas lets us inspect and manipulate that table before giving it to fast.ai.

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
procs = [Categorify, FillMissing, Normalize]

cat_names = ["Pclass", "Sex", "Embarked"]
cont_names = ["Age", "SibSp", "Parch", "Fare"]
y_names = "Survived"

dls = TabularDataLoaders.from_df(
    df,
    procs=procs,
    cat_names=cat_names,
    cont_names=cont_names,
    y_names=y_names,
    y_block=CategoryBlock,
    valid_pct=0.2,
    seed=15
)

In [8]:
dls.show_batch()

In [9]:
learn = tabular_learner(
    dls,
    metrics=accuracy
)
learn.fit_one_cycle(5)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>accuracy</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.696327</td><td>0.668553</td><td>0.713483</td><td>00:00</td></tr><tr><td>1</td><td>0.615567</td><td>0.624755</td><td>0.724719</td><td>00:00</td></tr><tr><td>2</td><td>0.611000</td><td>0.624528</td><td>0.713483</td><td>00:00</td></tr><tr><td>3</td><td>0.587554</td><td>0.603646</td><td>0.713483</td><td>00:00</td></tr><tr><td>4</td><td>0.574788</td><td>0.590410</td><td>0.730337</td><td>00:00</td></tr></tbody></table></div>